variables:
  VERSION: "2.1.0"
  NAME: PostalCodes.$VERSION.$CI_JOB_ID
  ARTIFACTORY: "https://artifactory.cimpress.io/artifactory/api/nuget/nuget-release-local;cost_center=0000263302;bu=CimpressTechnology;team_name=Vltava;contact_email=QuoterSupport@cimpress.com/"
  
stages:
  - build
  - publish

build:
  stage: build
  script:
#    - dotnet build --configuration Release -f net45      
    - dotnet build --configuration Release -f netcoreapp2.1     
    - dotnet test src/PostalCodes.UnitTests/PostalCodes.UnitTests.csproj
  tags:
    - netcore
  artifacts:
    paths:
      - src/
    expire_in: 1 week
    
publish:
  stage: publish
  only:
    - master
    - production
  script:
    - nuget pack "PostalCodes.Net.nuspec" -Verbosity detailed -Version $VERSION.$CI_JOB_ID
    - nuget sources Update -Name Artifactory -Source $ARTIFACTORY -ConfigFile nuget.config
    - nuget setapikey $ARTIFACTORY_USER:$ARTIFACTORY_PASS -Source Artifactory -ConfigFile nuget.config -Verbosity quiet
    - nuget push "$NAME.nupkg" -Source Artifactory -NonInteractive -ConfigFile nuget.config
  tags:
    - netcore