variables:
  VERSION: 2.1.0
  PC_VERSION: $VERSION.$CI_JOB_ID 
  NAME: PostalCodes
  ARTIFACTORY: "https://artifactory.cimpress.io/artifactory/api/nuget/nuget-release-local;cost_center=0000263302;bu=CimpressTechnology;team_name=Vltava;contact_email=QuoterSupport@cimpress.com/"
  
stages:
  - build
  - publish

build:
  stage: build
  script:
    - dotnet build --configuration Release -f net45      
    - dotnet build --configuration Release -f netcoreapp2.1     
    - dotnet test src/PostalCodes.UnitTests/PostalCodes.UnitTests.csproj
  tags:
#   - netcore
    - qp
    - windows
  artifacts:
    paths:
      - src/
    expire_in: 1 week
    
publish:
  stage: publish
  only:
    - master
    - production
  script:
    - nuget pack "PostalCodes.Net.nuspec" -Verbosity detailed -Version $PC_VERSION
    - nuget sources Update -Name Artifactory -Source $ARTIFACTORY -ConfigFile nuget.config
    - nuget setapikey "$ARTIFACTORY_USER`:$ARTIFACTORY_PASS" -Source Artifactory -ConfigFile nuget.config -Verbosity quiet # win version ` escapes the ":", should be removed if run on linux
    - nuget push "PostalCodes.$PC_VERSION.nupkg" -Source Artifactory -NonInteractive -ConfigFile nuget.config
  tags:
#   - netcore
    - qp
    - windows