using System.Collections.Generic;

namespace PostalCodes
{
	internal static class Iso3166Countries
	{
		internal static HashSet<Iso3166Country> Countries = new HashSet<Iso3166Country> {
			new Iso3166Country ("AA", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("AB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("AC", "Ascension Island", Iso3166CountryCodeStatus.ExceptionallyReserved),
			new Iso3166Country ("AD", "Andorra", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AE", "United Arab Emirates", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AF", "Afghanistan", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AG", "Antigua and Barbuda", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("AI", "Anguilla", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("AK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("AL", "Albania", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AM", "Armenia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AN", "Netherlands Antilles", Iso3166CountryCodeStatus.TransitionallyReserved, new [] { "CW", "BQ", "SX" }),
			new Iso3166Country ("AO", "Angola", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AP", "African Regional Industrial Property Organization", Iso3166CountryCodeStatus.NotUsed),
			new Iso3166Country ("AQ", "Antarctica", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AR", "Argentina", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AS", "American Samoa", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AT", "Austria", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AU", "Australia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("AW", "Aruba", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AX", "Åland Islands", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("AY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("AZ", "Azerbaijan", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BA", "Bosnia and Herzegovina", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BB", "Barbados", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BC", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("BD", "Bangladesh", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BE", "Belgium", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BF", "Burkina Faso", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BG", "Bulgaria", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BH", "Bahrain", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BI", "Burundi", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BJ", "Benin", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("BL", "Saint Barthélemy", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BM", "Bermuda", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BN", "Brunei Darussalam", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BO", "Bolivia, Plurinational State of", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("BQ", "Bonaire, Sint Eustatius and Saba", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BR", "Brazil", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BS", "Bahamas", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BT", "Bhutan", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BU", "Burma", Iso3166CountryCodeStatus.TransitionallyReserved),
			new Iso3166Country ("BV", "Bouvet Island", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BW", "Botswana", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BX", "Benelux Trademarks and Design Offices", Iso3166CountryCodeStatus.NotUsed),
			new Iso3166Country ("BY", "Belarus", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("BZ", "Belize", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CA", "Canada", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("CC", "Cocos (Keeling) Islands", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CD", "Congo, the Democratic Republic of the", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CE", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("CF", "Central African Republic", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CG", "Congo", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CH", "Switzerland", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CI", "Côte d'Ivoire", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("CK", "Cook Islands", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CL", "Chile", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CM", "Cameroon", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CN", "China", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CO", "Colombia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CP", "Clipperton Island", Iso3166CountryCodeStatus.ExceptionallyReserved),
			new Iso3166Country ("CQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("CR", "Costa Rica", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CS", "Serbia and Montenegro", Iso3166CountryCodeStatus.TransitionallyReserved),
			new Iso3166Country ("CT", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("CU", "Cuba", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CV", "Cabo Verde", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CW", "Curaçao", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CX", "Christmas Island", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CY", "Cyprus", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("CZ", "Czech Republic", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("DA", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DC", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DE", "Germany", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("DF", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DG", "Diego Garcia", Iso3166CountryCodeStatus.ExceptionallyReserved),
			new Iso3166Country ("DH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DI", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DJ", "Djibouti", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("DK", "Denmark", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("DL", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DM", "Dominica", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("DN", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DO", "Dominican Republic", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("DP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DR", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DS", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DT", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DU", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DW", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("DY", "Benin", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("DZ", "Algeria", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("EA", "Ceuta, Melilla", Iso3166CountryCodeStatus.ExceptionallyReserved),
			new Iso3166Country ("EB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("EC", "Ecuador", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("ED", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("EE", "Estonia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("EF", "Union of Countries under the European Community Patent Convention", Iso3166CountryCodeStatus.NotUsed),
			new Iso3166Country ("EG", "Egypt", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("EH", "Western Sahara", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("EI", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("EJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("EK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("EL", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("EM", "European Trademark Office", Iso3166CountryCodeStatus.NotUsed),
			new Iso3166Country ("EN", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("EO", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("EP", "European Patent Organization", Iso3166CountryCodeStatus.NotUsed),
			new Iso3166Country ("EQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ER", "Eritrea", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("ES", "Spain", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("ET", "Ethiopia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("EU", "European Union", Iso3166CountryCodeStatus.ExceptionallyReserved),
			new Iso3166Country ("EV", "Eurasian Patent Organization", Iso3166CountryCodeStatus.NotUsed),
			new Iso3166Country ("EW", "Estonia", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("EX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("EY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("EZ", "Eurozone", Iso3166CountryCodeStatus.ExceptionallyReserved),
			new Iso3166Country ("FA", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FC", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FE", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FF", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FG", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FI", "Finland", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("FJ", "Fiji", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("FK", "Falkland Islands (Malvinas)", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("FL", "Liechtenstein", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("FM", "Micronesia, Federated States of", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("FN", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FO", "Faroe Islands", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("FP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FR", "France", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("FS", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FT", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FU", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FW", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FX", "France, Metropolitan", Iso3166CountryCodeStatus.ExceptionallyReserved),
			new Iso3166Country ("FY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("FZ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("GA", "Gabon", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GB", "United Kingdom of Great Britain and Northern Ireland", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GC", "Patent Office of the Cooperation Council for the Arab States of the Gulf (GCC)", Iso3166CountryCodeStatus.NotUsed),
			new Iso3166Country ("GD", "Grenada", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GE", "Georgia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GF", "French Guiana", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GG", "Guernsey", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GH", "Ghana", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GI", "Gibraltar", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("GK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("GL", "Greenland", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GM", "Gambia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GN", "Guinea", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GO", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("GP", "Guadeloupe", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GQ", "Equatorial Guinea", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GR", "Greece", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GS", "South Georgia and the South Sandwich Islands", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GT", "Guatemala", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GU", "Guam", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("GW", "Guinea-Bissau", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("GY", "Guyana", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("GZ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HA", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HC", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HE", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HF", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HG", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HI", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HK", "Hong Kong", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("HL", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HM", "Heard Island and McDonald Islands", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("HN", "Honduras", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("HO", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HR", "Croatia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("HS", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HT", "Haiti", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("HU", "Hungary", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("HV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HW", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("HZ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("IA", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("IB", "International Bureau of WIPO", Iso3166CountryCodeStatus.NotUsed),
			new Iso3166Country ("IC", "Canary Islands", Iso3166CountryCodeStatus.ExceptionallyReserved),
			new Iso3166Country ("ID", "Indonesia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("IE", "Ireland", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("IF", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("IG", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("IH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("II", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("IJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("IK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("IL", "Israel", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("IM", "Isle of Man", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("IN", "India", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("IO", "British Indian Ocean Territory", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("IP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("IQ", "Iraq", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("IR", "Iran, Islamic Republic of", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("IS", "Iceland", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("IT", "Italy", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("IU", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("IV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("IW", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("IX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("IY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("IZ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JA", "Jamaica", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("JB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JC", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JE", "Jersey", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("JF", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JG", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JI", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JL", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JM", "Jamaica", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("JN", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JO", "Jordan", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("JP", "Japan", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("JQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JR", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JS", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JT", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JU", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JW", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("JZ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KA", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KC", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KE", "Kenya", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("KF", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KG", "Kyrgyzstan", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("KH", "Cambodia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("KI", "Kiribati", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("KJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KL", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KM", "Comoros", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("KN", "Saint Kitts and Nevis", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("KO", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KP", "Korea, Democratic People's Republic of", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("KQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KR", "Korea, Republic of", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("KS", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KT", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KU", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KW", "Kuwait", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("KX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("KY", "Cayman Islands", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("KZ", "Kazakhstan", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("LA", "Lao People's Democratic Republic", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("LB", "Lebanon", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("LC", "Saint Lucia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("LD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("LE", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("LF", "Libya Fezzan", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("LG", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("LH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("LI", "Liechtenstein", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("LJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("LK", "Sri Lanka", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("LL", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("LM", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("LN", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("LO", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("LP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("LQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("LR", "Liberia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("LS", "Lesotho", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("LT", "Lithuania", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("LU", "Luxembourg", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("LV", "Latvia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("LW", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("LX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("LY", "Libya", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("LZ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("MA", "Morocco", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("MC", "Monaco", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MD", "Moldova, Republic of", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("ME", "Montenegro", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MF", "Saint Martin (French part)", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MG", "Madagascar", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MH", "Marshall Islands", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MI", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("MJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("MK", "Macedonia, the former Yugoslav Republic of", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("ML", "Mali", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MM", "Myanmar", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MN", "Mongolia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MO", "Macao", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MP", "Northern Mariana Islands", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MQ", "Martinique", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MR", "Mauritania", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MS", "Montserrat", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MT", "Malta", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MU", "Mauritius", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MV", "Maldives", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MW", "Malawi", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MX", "Mexico", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MY", "Malaysia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("MZ", "Mozambique", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("NA", "Namibia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("NB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("NC", "New Caledonia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("ND", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("NE", "Niger", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("NF", "Norfolk Island", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("NG", "Nigeria", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("NH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("NI", "Nicaragua", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("NJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("NK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("NL", "Netherlands", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("NM", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("NN", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("NO", "Norway", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("NP", "Nepal", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("NQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("NR", "Nauru", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("NS", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("NT", "Neutral Zone", Iso3166CountryCodeStatus.TransitionallyReserved),
			new Iso3166Country ("NU", "Niue", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("NV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("NW", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("NX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("NY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("NZ", "New Zealand", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("OA", "African Intellectual Property Organization", Iso3166CountryCodeStatus.NotUsed),
			new Iso3166Country ("OB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OC", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OE", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OF", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OG", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OI", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OL", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OM", "Oman", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("ON", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OO", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OR", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OS", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OT", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OU", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OW", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("OZ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("PA", "Panama", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("PC", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("PD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("PE", "Peru", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PF", "French Polynesia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PG", "Papua New Guinea", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PH", "Philippines", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PI", "Philippines", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("PJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("PK", "Pakistan", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PL", "Poland", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PM", "Saint Pierre and Miquelon", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PN", "Pitcairn", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PO", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("PP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("PQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("PR", "Puerto Rico", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PS", "Palestine, State of", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PT", "Portugal", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PU", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("PV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("PW", "Palau", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("PY", "Paraguay", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("PZ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("QA", "Qatar", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("QB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("QC", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("QD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("QE", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("QF", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("QG", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("QH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("QI", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("QJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("QK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("QL", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("QM", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("QN", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("QO", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("QP", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("QQ", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("QR", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("QS", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("QT", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("QU", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("QV", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("QW", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("QX", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("QY", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("QZ", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("RA", "Argentina", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("RB", "Bolivia/Botswana", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("RC", "China", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("RD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("RE", "Réunion", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("RF", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("RG", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("RH", "Haiti", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("RI", "Indonesia", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("RJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("RK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("RL", "Lebanon", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("RM", "Madagascar", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("RN", "Niger", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("RO", "Romania", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("RP", "Philippines", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("RQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("RR", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("RS", "Serbia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("RT", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("RU", "Russian Federation", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("RV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("RW", "Rwanda", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("RX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("RY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("RZ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("SA", "Saudi Arabia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SB", "Solomon Islands", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SC", "Seychelles", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SD", "Sudan", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SE", "Sweden", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SF", "Finland", Iso3166CountryCodeStatus.TransitionallyReserved),
			new Iso3166Country ("SG", "Singapore", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SH", "Saint Helena, Ascension and Tristan da Cunha", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SI", "Slovenia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SJ", "Svalbard and Jan Mayen", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SK", "Slovakia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SL", "Sierra Leone", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SM", "San Marino", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SN", "Senegal", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SO", "Somalia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("SQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("SR", "Suriname", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SS", "South Sudan", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("ST", "Sao Tome and Principe", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SU", "USSR", Iso3166CountryCodeStatus.ExceptionallyReserved),
			new Iso3166Country ("SV", "El Salvador", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SW", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("SX", "Sint Maarten (Dutch part)", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SY", "Syrian Arab Republic", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("SZ", "Swaziland", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TA", "Tristan da Cunha", Iso3166CountryCodeStatus.ExceptionallyReserved),
			new Iso3166Country ("TB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("TC", "Turks and Caicos Islands", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TD", "Chad", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TE", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("TF", "French Southern Territories", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TG", "Togo", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TH", "Thailand", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TI", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("TJ", "Tajikistan", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TK", "Tokelau", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TL", "Timor-Leste", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TM", "Turkmenistan", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TN", "Tunisia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TO", "Tonga", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TP", "East Timor", Iso3166CountryCodeStatus.TransitionallyReserved),
			new Iso3166Country ("TQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("TR", "Turkey", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TS", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("TT", "Trinidad and Tobago", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TU", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("TV", "Tuvalu", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TW", "Taiwan, Province of China", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("TX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("TY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("TZ", "Tanzania, United Republic of", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("UA", "Ukraine", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("UB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UC", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UE", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UF", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UG", "Uganda", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("UH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UI", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UK", "United Kingdom", Iso3166CountryCodeStatus.ExceptionallyReserved, new [] { "GB" }),
			new Iso3166Country ("UL", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UM", "United States Minor Outlying Islands", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("UN", "United Nations", Iso3166CountryCodeStatus.ExceptionallyReserved),
			new Iso3166Country ("UO", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UR", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("US", "United States of America", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("UT", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UU", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UW", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("UY", "Uruguay", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("UZ", "Uzbekistan", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("VA", "Holy See", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("VB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VC", "Saint Vincent and the Grenadines", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("VD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VE", "Venezuela, Bolivarian Republic of", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("VF", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VG", "Virgin Islands, British", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("VH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VI", "Virgin Islands, U.S.", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("VJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VL", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VM", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VN", "Viet Nam", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("VO", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VR", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VS", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VT", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VU", "Vanuatu", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("VV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VW", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("VZ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WA", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WC", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WE", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WF", "Wallis and Futuna", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("WG", "Grenada", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("WH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WI", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WL", "Saint Lucia", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("WM", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WN", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WO", "World Intellectual Property Organization", Iso3166CountryCodeStatus.NotUsed),
			new Iso3166Country ("WP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WR", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WS", "Samoa", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("WT", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WU", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WV", "Saint Vincent", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("WW", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("WZ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("XA", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XB", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XC", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XD", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XE", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XF", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XG", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XH", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XI", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XJ", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XK", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XL", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XM", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XN", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XO", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XP", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XQ", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XR", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XS", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XT", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XU", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XV", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XW", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XX", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XY", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("XZ", "", Iso3166CountryCodeStatus.UserAssigned),
			new Iso3166Country ("YA", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YC", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YE", "Yemen", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("YF", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YG", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YI", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YL", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YM", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YN", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YO", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YR", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YS", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YT", "Mayotte", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("YU", "Yugoslavia", Iso3166CountryCodeStatus.TransitionallyReserved),
			new Iso3166Country ("YV", "Venecuela", Iso3166CountryCodeStatus.IndeterminateReserved),
			new Iso3166Country ("YW", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("YZ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZA", "South Africa", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("ZB", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZC", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZD", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZE", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZF", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZG", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZH", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZI", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZJ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZK", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZL", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZM", "Zambia", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("ZN", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZO", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZP", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZQ", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZR", "Zaire", Iso3166CountryCodeStatus.TransitionallyReserved),
			new Iso3166Country ("ZS", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZT", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZU", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZV", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZW", "Zimbabwe", Iso3166CountryCodeStatus.OfficiallyAssigned),
			new Iso3166Country ("ZX", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZY", "", Iso3166CountryCodeStatus.Unassigned),
			new Iso3166Country ("ZZ", "", Iso3166CountryCodeStatus.UserAssigned),
		};
	}
}
