name: .NET Core
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test src/PostalCodes.UnitTests/PostalCodes.UnitTests.csproj
    - name: Publish
      uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      run: |
        nuget pack "PostalCodes.Net.nuspec" -Verbosity detailed -Version 3.1.0.6
        nuget push PostalCodes.3.1.0.6.nupkg -Source https://api.nuget.org/v3/index.json -NonInteractive -ConfigFile nuget.config