name: .NET Core
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["2.2.108", "8.0.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 2.2.108
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test src/PostalCodes.UnitTests/PostalCodes.UnitTests.csproj
